services:
  nginx_proxy:
    image: nginx:latest
    container_name: link_nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      link-io:
        aliases:
          - "proxy"

  link_api:
    image: node:latest
    environment:
      VIRTUAL_HOST: dev.api.link.io
      VIRTUAL_PORT: 5000
    container_name: link_api
    hostname: link_api
    expose:
      - 5000
    volumes:
      - ./link_api:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    networks:
      link-io:
        aliases:
          - "dev.api.link.io"

  link_app:
    image: node:22.11.0
    environment:
      VIRTUAL_HOST: dev.app.link.io
      VIRTUAL_PORT: 3000
    container_name: link_app
    hostname: link_app
    expose:
      - 3000
    volumes:
      - ./link_app:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    networks:
      link-io:
        aliases:
          - "dev.app.link.io"

networks:
  link-io:
    driver: bridge
